#!/usr/bin/python3

# __init__.py
# Date:  16/03/2021
# Author: Eugeniu Costetchi
# Email: costezki.eugen@gmail.com

""" """

COVID_EUROVOC_SEARCH_TERMS = ["EU financing",
                              "innovation",
                              "free movement of persons",
                              "illness",
                              "respiratory disease",
                              "infectious disease",
                              "labour market",
                              "disease prevention",
                              "health control",
                              "applied research",
                              "medical research",
                              "health risk",
                              "public health",
                              "tourism",
                              "air transport",
                              "research and development",
                              "aid to undertakings",
                              "occupational health",
                              "free movement of workers",
                              "standard of living",
                              "health policy",
                              "public awareness campaign",
                              "working conditions",
                              "communications policy",
                              "economic consequence",
                              "vaccination",
                              "economic activity",
                              "economic support",
                              "aid to disadvantaged groups",
                              "health legislation",
                              "quality of life",
                              "social sciences",
                              "economic aid",
                              "European Centre for Disease Prevention and Control",
                              "living conditions",
                              "social situation",
                              "organisation of health care",
                              "teleworking",
                              "job preservation",
                              "state of emergency",
                              "working environment",
                              "health service",
                              "protective equipment",
                              "epidemic",
                              "social participation",
                              "epidemiology",
                              "aid programme",
                              "restriction of liberty",
                              "basic needs",
                              "public hygiene",
                              "mass media",
                              "social impact",
                              "freedom of movement",
                              "patient rights",
                              "social well-being",
                              "socioeconomic conditions",
                              "endemic disease",
                              "distance learning",
                              "self-regulation",
                              "disinformation",
                              "social media",
                              "crisis management",
                              "e-Health",
                              "patient safety",
                              "hospital infection",
                              "viral disease",
                              "coronavirus disease",
                              "disease surveillance",
                              "virus",
                              "covid",
                              "illness",
                              "pandemic",
                              "crisis",
                              "infectious disease"]
