# This is a  workflow that will run the pylint code grading

name: pylint quality code

# Controls when the action will run. Triggers of this workflow are on push on a feature branches or pull request
# on feature branches created from master
on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    name: "Check code quality issues"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          make install
          pip install pylint
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
          envkey_VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "tests"
          use-pylint: true
          use-pycodestyle: true
          use-flake8: true
          use-black: true
          use-mypy: true
          use-isort: true
          extra-pylint-options: "--max-module-lines=212 --disable=I,R,C,W"
          extra-pycodestyle-options: ""
          extra-flake8-options: ""
          extra-black-options: ""
          extra-mypy-options: ""
          extra-isort-options: ""