# This is a  workflow that will run the all tests and upload to Codecov

name: all tests

# Controls when the action will run. Trigger of this will run on any commit/merge in master
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    name: "Run tests"
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          make install
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
          envkey_VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      - name: Run tests
        run: make test-all
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true

#      - uses: ricardochaves/python-lint@v1.4.0
#        with:
#          python-root-list: "tests"
#          use-pylint: true
#          use-pycodestyle: true
#          use-flake8: true
#          use-black: true
#          use-mypy: true
#          use-isort: true
#          extra-pylint-options: "--max-module-lines=250 --disable=I,R,C,W"
#          extra-pycodestyle-options: ""
#          extra-flake8-options: ""
#          extra-black-options: ""
#          extra-mypy-options: ""
#          extra-isort-options: ""